-- MySQL Script generated by MySQL Workbench
-- Sun Sep 15 20:49:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DealerStat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DealerStat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DealerStat` DEFAULT CHARACTER SET utf8 ;
USE `DealerStat` ;

-- -----------------------------------------------------
-- Table `DealerStat`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DealerStat`.`User` (
  `user_id` INT NOT NULL,
  `first_name` TINYTEXT NOT NULL,
  `last_name` TINYTEXT NULL,
  `password` VARCHAR(45) NULL,
  `email` TINYTEXT NULL,
  `created_at` DATETIME NULL,
  `role` ENUM('admin', 'trader', 'anon') NOT NULL DEFAULT 'anon',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DealerStat`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DealerStat`.`Game` (
  `game_id` INT NOT NULL,
  `name` TINYTEXT NULL,
  PRIMARY KEY (`game_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DealerStat`.`GameObject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DealerStat`.`GameObject` (
  `gameobject_id` INT NOT NULL,
  `title` TEXT NULL,
  `text` TEXT NULL,
  `status` ENUM('sold', 'available') NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`gameobject_id`),
  INDEX `fk_GameObject_Game1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_GameObject_Game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `DealerStat`.`Game` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DealerStat`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DealerStat`.`Comment` (
  `comment_id` INT NOT NULL,
  `message` TEXT NULL,
  `created_at` DATETIME NULL,
  `approved` TINYINT NULL,
  `author_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `rate` VARCHAR(45) NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_Comment_User1_idx` (`author_id` ASC) VISIBLE,
  INDEX `fk_Comment_GameObject1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`author_id`)
    REFERENCES `DealerStat`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_GameObject1`
    FOREIGN KEY (`post_id`)
    REFERENCES `DealerStat`.`GameObject` (`gameobject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DealerStat`.`User_has_GameObject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DealerStat`.`User_has_GameObject` (
  `user_id` INT NOT NULL,
  `gameobject_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `gameobject_id`),
  INDEX `fk_User_has_GameObject_GameObject1_idx` (`gameobject_id` ASC) VISIBLE,
  INDEX `fk_User_has_GameObject_User1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_GameObject_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `DealerStat`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_GameObject_GameObject1`
    FOREIGN KEY (`gameobject_id`)
    REFERENCES `DealerStat`.`GameObject` (`gameobject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `DealerStat` ;

-- -----------------------------------------------------
-- Placeholder table for view `DealerStat`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DealerStat`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `DealerStat`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DealerStat`.`view1`;
USE `DealerStat`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

Insert into user value (3, 'eldarian', '123456')