-- MySQL Script generated by MySQL Workbench
-- Thu Sep 19 16:29:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DealerStat
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DealerStat` ;

-- -----------------------------------------------------
-- Schema DealerStat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DealerStat` DEFAULT CHARACTER SET utf8 ;
USE `DealerStat` ;

-- -----------------------------------------------------
-- Table `DealerStat`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DealerStat`.`User` ;

CREATE TABLE IF NOT EXISTS `DealerStat`.`User` (
                                                   `id` INT NOT NULL,
                                                   `name` TINYTEXT NOT NULL,
                                                   `password` VARCHAR(45) NULL,
                                                   `email` TINYTEXT NULL,
                                                   `created_at` DATETIME NULL,
                                                   `role` ENUM('admin', 'trader', 'anon') NOT NULL DEFAULT 'anon',
                                                   PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DealerStat`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DealerStat`.`Game` ;

CREATE TABLE IF NOT EXISTS `DealerStat`.`Game` (
                                                   `id` INT NOT NULL,
                                                   `name` TINYTEXT NULL,
                                                   PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DealerStat`.`GameObject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DealerStat`.`GameObject` ;

CREATE TABLE IF NOT EXISTS `DealerStat`.`GameObject` (
                                                         `id` INT NOT NULL,
                                                         `title` TEXT NULL,
                                                         `text` TEXT NULL,
                                                         `status` ENUM('sold', 'available') NULL,
                                                         `created_at` DATETIME NULL,
                                                         `updated_at` DATETIME NULL,
                                                         `game_id` INT NOT NULL,
                                                         `trader_id` INT NOT NULL,
                                                         PRIMARY KEY (`id`, `trader_id`),
                                                         INDEX `fk_GameObject_Game1_idx` (`game_id` ASC) VISIBLE,
                                                         INDEX `fk_GameObject_User1_idx` (`trader_id` ASC) VISIBLE,
                                                         CONSTRAINT `fk_GameObject_Game1`
                                                             FOREIGN KEY (`game_id`)
                                                                 REFERENCES `DealerStat`.`Game` (`id`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION,
                                                         CONSTRAINT `fk_GameObject_User1`
                                                             FOREIGN KEY (`trader_id`)
                                                                 REFERENCES `DealerStat`.`User` (`id`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DealerStat`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DealerStat`.`Comment` ;

CREATE TABLE IF NOT EXISTS `DealerStat`.`Comment` (
                                                      `id` INT NOT NULL,
                                                      `message` TEXT NULL,
                                                      `created_at` DATETIME NULL,
                                                      `approved` TINYINT NULL,
                                                      `author_id` INT NOT NULL,
                                                      `gameObject_id` INT NOT NULL,
                                                      `rate` VARCHAR(45) NULL,
                                                      PRIMARY KEY (`id`),
                                                      INDEX `fk_Comment_User1_idx` (`author_id` ASC) VISIBLE,
                                                      INDEX `fk_Comment_GameObject1_idx` (`gameObject_id` ASC) VISIBLE,
                                                      CONSTRAINT `fk_Comment_User1`
                                                          FOREIGN KEY (`author_id`)
                                                              REFERENCES `DealerStat`.`User` (`id`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_Comment_GameObject1`
                                                          FOREIGN KEY (`gameObject_id`)
                                                              REFERENCES `DealerStat`.`GameObject` (`id`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION)
    ENGINE = InnoDB;

USE `DealerStat` ;

-- -----------------------------------------------------
-- Placeholder table for view `DealerStat`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DealerStat`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `DealerStat`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DealerStat`.`view1`;
DROP VIEW IF EXISTS `DealerStat`.`view1` ;
USE `DealerStat`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
